[project]
name = "whatsapp-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inquirerpy>=0.3.4",
    "jinja2>=3.1.4",
]

[tool.uv]
dev-dependencies = [
    "djlint>=1.36.1",
    "mypy>=1.13.0",
]
